# Introduction to PyTorch -- Solutions

In [2]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [3]:
A=torch.Tensor( [ [1,2] , [3,4] ] )
B=torch.Tensor( [ [10,20] , [30,40] ] )

C=A+B

print(A)
print('')
print(B)
print('')
print(C)

tensor([[1., 2.],
        [3., 4.]])

tensor([[10., 20.],
        [30., 40.]])

tensor([[11., 22.],
        [33., 44.]])


### Print the sizes, dimension, and type of the matrix A. Remember, the commands are size(), dim() and type()

In [4]:
print( A.size() )
print( A.dim() )
print( A.type() )

torch.Size([2, 2])
2
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [5]:
A=A.long()
print(A)
print(A.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [6]:
A=torch.rand(5,2,4)
print(A)
print(A.type())
print(A.dim())
print(A.size())
print(A.size(1))

tensor([[[0.9352, 0.5620, 0.5632, 0.1376],
         [0.9416, 0.6177, 0.0414, 0.1272]],

        [[0.6560, 0.6309, 0.4658, 0.6593],
         [0.9723, 0.5108, 0.2144, 0.9618]],

        [[0.3162, 0.7408, 0.8476, 0.5557],
         [0.7965, 0.1295, 0.1915, 0.3873]],

        [[0.9284, 0.9876, 0.8609, 0.4669],
         [0.9431, 0.8253, 0.1314, 0.4267]],

        [[0.0851, 0.2073, 0.9871, 0.2162],
         [0.6092, 0.6204, 0.2411, 0.7048]]])
torch.FloatTensor
3
torch.Size([5, 2, 4])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [7]:
A=torch.zeros(2,3,4,5)
print(A)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])


In [8]:
import numpy as np
import math
M = np.array([[1,0.4], [0.4,1]])
print(M)

[[1.  0.4]
 [0.4 1. ]]


In [9]:
Minv = np.linalg.inv(M)

In [10]:
print(Minv)

[[ 1.19047619 -0.47619048]
 [-0.47619048  1.19047619]]


In [11]:
np.sqrt(Minv)

/var/folders/mq/9smvx9v10lz9nfgprhq0lngw0000gn/T/ipykernel_3066/3356190861.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(Minv)


array([[1.09108945,        nan],
       [       nan, 1.09108945]])

###Using Numpy

In [12]:
array1 = np.array([[-1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), 1/np.sqrt(2)]])
print(array1)

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [13]:
array2 = np.array([[0.84,0],[0, 1.291]])
print(array2)

[[0.84  0.   ]
 [0.    1.291]]


##UsingPytorch

In [14]:
# Calculate the reciprocal square root of 2 as a scalar
rsqrt_2 = 1 / torch.sqrt(torch.tensor(2.0))

# Create the tensor using the scalar value
array3 = torch.Tensor([[-rsqrt_2, rsqrt_2], [rsqrt_2, rsqrt_2]])

print(array3)

#array3 = torch.Tensor([[-rsqrt(2), rsqrt(2)], [rsqrt(2),rsqrt(2)]])

tensor([[-0.7071,  0.7071],
        [ 0.7071,  0.7071]])


In [15]:
A = torch.Tensor([[1,1], [2,2]])

In [16]:
print(A)

tensor([[1., 1.],
        [2., 2.]])


In [17]:
array3 = np.array([[-1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), 1/np.sqrt(2)]])
print(array3)

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [18]:
MatMul = np.matmul(array1,array2,array3)

In [19]:
print(MatMul)

[[-0.5939697   0.91287485]
 [ 0.5939697   0.91287485]]


In [20]:
array1 = np.array([[-1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), 1/np.sqrt(2)]])
print(array1)

array2 = np.array([[1.291,0],[0, 0.84]])
print(array2)

array3 = np.linalg.inv(array1)
print(array3)

# Perform matrix multiplication using @ operator
result = array1 @ array2 @ array3
print("Result of multiplying Array1, Array2, and Array3:\n", result)

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[[1.291 0.   ]
 [0.    0.84 ]]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
Result of multiplying Array1, Array2, and Array3:
 [[ 1.0655 -0.2255]
 [-0.2255  1.0655]]


In [21]:
A11 = np.array([[1, 0.4], [0.4, 1.0]])
print("A11:\n", A11)

# Eigenvalue decomposition
eigenvalues, eigenvectors = np.linalg.eigh(A11)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Inverse square root of the eigenvalues
inv_sqrt_eigenvalues = np.diag(1 / np.sqrt(eigenvalues))
print("Inverse square root of eigenvalues:\n", inv_sqrt_eigenvalues)

# Reconstruct A11^{-1/2}
A11_inv_sqrt = eigenvectors @ inv_sqrt_eigenvalues @ eigenvectors.T
print("A11^{-1/2}:\n", A11_inv_sqrt)


A11:
 [[1.  0.4]
 [0.4 1. ]]
Eigenvalues:
 [0.6 1.4]
Eigenvectors:
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
Inverse square root of eigenvalues:
 [[1.29099445 0.        ]
 [0.         0.84515425]]
A11^{-1/2}:
 [[ 1.06807435 -0.2229201 ]
 [-0.2229201   1.06807435]]
