# Introduction to PyTorch -- Solutions

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [2]:
A=torch.Tensor( [ [1,2] , [3,4] ] )
B=torch.Tensor( [ [10,20] , [30,40] ] )

C=A+B

print(A)
print('')
print(B)
print('')
print(C)

tensor([[1., 2.],
        [3., 4.]])

tensor([[10., 20.],
        [30., 40.]])

tensor([[11., 22.],
        [33., 44.]])


### Print the sizes, dimension, and type of the matrix A. Remember, the commands are size(), dim() and type()

In [3]:
print( A.size() )
print( A.dim() )
print( A.type() )

torch.Size([2, 2])
2
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [4]:
A=A.long()
print(A)
print(A.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [5]:
A=torch.rand(5,2,4)
print(A)
print(A.type())
print(A.dim())
print(A.size())
print(A.size(1))

tensor([[[0.8701, 0.3568, 0.1633, 0.7290],
         [0.2824, 0.7079, 0.1837, 0.3675]],

        [[0.1442, 0.3833, 0.7606, 0.4600],
         [0.6259, 0.0662, 0.8280, 0.2585]],

        [[0.4741, 0.3761, 0.7646, 0.5612],
         [0.9687, 0.1040, 0.1612, 0.9647]],

        [[0.3693, 0.6893, 0.6190, 0.2432],
         [0.3433, 0.7791, 0.9568, 0.5573]],

        [[0.6972, 0.2924, 0.9546, 0.8517],
         [0.6203, 0.2883, 0.1762, 0.4889]]])
torch.FloatTensor
3
torch.Size([5, 2, 4])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [ ]:
A=torch.zeros(2,3,4,5)
print(A)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
